xilinx-zynqmp: update README for BOOT.BIN generation
Issue: LINCD-14702

Add the missing line "CUSTOMER_RECIPES:xilinx += 'u-boot-xlnx'" to fix
the building error:

ERROR: Nothing PROVIDES 'u-boot-xlnx' (but layers/meta-xilinx/meta-xilinx-core/recipes-bsp/bootbin/xilinx-bootbin_1.0.bb DEPENDS on or otherwise requires it)

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>